const ahuUnits={
  'AH-3F-09A':{site:'main',siteName:'巨城本館',bms:'iFIX',type:'EC FAN',baseline:1280,actual:980,hours:720,temp:23.8,tempCompliance:98.2,co2:620,fan:68,fanRec:52,valve:28,shadow:16.2,confidence:92},
  'AH-4F-02':{site:'main',siteName:'巨城本館',bms:'iFIX',type:'VFD',baseline:1420,actual:1085,hours:704,temp:24.1,tempCompliance:97.6,co2:650,fan:71,fanRec:56,valve:31,shadow:14.8,confidence:89},
  'AH-2F-03':{site:'creative',siteName:'創藝大樓',bms:'WebCTRL',type:'EC FAN',baseline:990,actual:742,hours:688,temp:23.6,tempCompliance:98.8,co2:590,fan:62,fanRec:49,valve:26,shadow:17.4,confidence:94},
  'AH-B1-01':{site:'main',siteName:'巨城本館',bms:'iFIX',type:'VFD',baseline:1150,actual:892,hours:736,temp:24.3,tempCompliance:96.9,co2:680,fan:66,fanRec:54,valve:34,shadow:13.2,confidence:87},
  'AH-RF-01':{site:'cinema',siteName:'威秀影城',bms:'WebCTRL',type:'VFD',baseline:1360,actual:1040,hours:612,temp:24.0,tempCompliance:98.0,co2:710,fan:73,fanRec:58,valve:37,shadow:12.6,confidence:90}
};
Object.assign(state,{ahuSite:'all',ahuType:'all',ahuPeriod:'year',ahuUnit:'AH-3F-09A',ahuRange:'month'});

function ahuTabs(active){
  const items=[['ahu-overview','06-1 改善總覽'],['ahu-unit','06-2 單台驗證'],['ahu-shadow','06-3 AI Shadow'],['ahu-contribution','06-4 AI 貢獻'],['ahu-health','06-5 舒適度・健康']];
  return `<div class="ahu-subtabs">${items.map(([v,t])=>`<button class="ahu-tab ${active===v?'active':''}" data-ahu-page="${v}">${t}</button>`).join('')}<div class="ahu-year">📅 2026 年</div></div>`;
}
function ahuPageHead(page,title,sub){return hero(title,sub)+ahuTabs(page)+`<div class="ahu-page-note">Demo Data｜示範數值，正式系統將依現場 BMS / EMS 與 M&amp;V 基線計算</div>`;}
function ahuUnitSelect(){return `<select id="ahuUnitSelect">${Object.entries(ahuUnits).map(([id,u])=>`<option value="${id}" ${state.ahuUnit===id?'selected':''}>${id}｜${u.siteName}｜${u.type}</option>`).join('')}</select>`;}
function ahuSiteSeg(){return `<div class="seg" data-control="ahuSite">${[['all','全部'],['main','巨城本館'],['creative','創藝大樓'],['cinema','威秀影城']].map(([v,t])=>`<button data-value="${v}" class="${state.ahuSite===v?'active':''}">${t}</button>`).join('')}</div>`;}
function ahuTypeSeg(){return `<div class="seg" data-control="ahuType">${[['all','全部'],['ec','EC FAN'],['vfd','VFD']].map(([v,t])=>`<button data-value="${v}" class="${state.ahuType===v?'active':''}">${t}</button>`).join('')}</div>`;}
function ahuPeriodSeg(){return `<div class="seg" data-control="ahuPeriod">${[['year','年'],['quarter','季'],['month','月']].map(([v,t])=>`<button data-value="${v}" class="${state.ahuPeriod===v?'active':''}">${t}</button>`).join('')}</div>`;}
function unitSeries(base,actual,n=16){const shape=[.91,.95,1.00,.96,.93,1.04,1.06,1.02,.98,.96,1.03,1.01,.97,.94,1.00,.96];return {baseline:shape.slice(0,n).map((m,i)=>Math.round(base*m*(1+(i%4-1.5)*.008))),actual:shape.slice(0,n).map((m,i)=>Math.round(actual*m*(1+(i%3-1)*.007)))};}
function shadowSeries(u,n=16){const s=unitSeries(u.baseline,u.actual,n);return {...s,recommended:s.actual.map((v,i)=>Math.round(v*(1-u.shadow/100)*(1+(i%5-2)*.004)))};}
function ahuSavingsBar(){return `<div class="chart-box ahu-chart-md">${svgBars([{name:'改善前',data:[62400,98200],color:'#a8b9c9'},{name:'改善後',data:[47800,74600],color:'#1597f5'}],['EC FAN (12台)','VFD (17台)'],{max:120000})}</div><div class="ahu-statusbar"><span class="pill-chip good">EC FAN ▼23%</span><span class="pill-chip good">VFD ▼24%</span><span class="card-sub">相似負載與營業條件標準化後比較</span></div>`;}
function ahuDonutBlock(){return `<div class="ahu-donut-wrap"><div class="ahu-donut"><div class="ahu-donut-center">1,280,500<small>kWh<br>2026 累計節電</small></div></div><div class="ahu-legend"><span><i style="background:var(--blue)"></i>VFD 改善　52%</span><span><i style="background:var(--green)"></i>EC FAN 改善　32%</span><span><i style="background:var(--purple)"></i>AI 建議採納後　11%</span><span><i style="background:var(--amber)"></i>其他運轉調整　5%</span></div></div>`;}

function renderAhuOverview(){
  const months=['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'];
  return ahuPageHead('ahu-overview','空調箱改善總覽','整合 EC FAN・VFD 硬體升級與 AI 最佳化建議，量化改善成果與後續節能潛力。')+
  `<div class="ahu-controls"><label>場域：${ahuSiteSeg()}</label><label>設備型態：${ahuTypeSeg()}</label><label>期間：${ahuPeriodSeg()}</label><label style="margin-left:auto">年份：<span class="control-btn active">2026 年⌄</span></label></div>
  <div class="ahu-kpi-grid">${kpi('✤','納管 AHU<br>(空調箱總數)','29','台','全數納入能源管理','blue')}${kpi('🍃','EC FAN 設備<br>(高效率風機)','12','台','41%　設備占比','good','green')}${kpi('▦','VFD 設備<br>(變頻控制)','17','台','59%　設備占比','blue')}${kpi('ϟ','累計節電量<br>(2026)','1,280,500','kWh','▲ 12%　較去年','good')}${kpi('▥','平均節電率<br>(相較改善前)','18.6','%','▲ 6.2%　較去年','good')}${kpi('🧠','AI 尚有潛力<br>(Shadow Opportunity)','356,000','kWh','約 13% 可再優化','warn')}</div>
  <div class="ahu-three-grid">
    <section class="card ahu-card-pad"><div class="card-head"><div class="card-title ahu-panel-title"><span class="spark">✤</span>AHU 設備總覽</div>${pill('運轉正常','good')}</div><div style="display:flex;gap:18px;align-items:center"><div style="font-size:42px;font-weight:900;color:var(--ink)">29<small style="font-size:14px"> 台 AHU</small></div><div class="mini-list" style="flex:1"><div class="mini-row"><span class="rank-dot good">●</span><div><b>正常運轉 24 台</b><small>83%</small></div></div><div class="mini-row"><span class="rank-dot">●</span><div><b>AI 優化觀察中 3 台</b><small>10%</small></div></div><div class="mini-row"><span class="rank-dot warn">●</span><div><b>待改善 2 台</b><small>7%</small></div></div></div></div><div class="ahu-fleet-bar"><i class="good"></i><i class="blue"></i><i class="warn"></i></div></section>
    ${card('<span class="spark">▥</span>EC FAN vs VFD 改善成效比較',ahuSavingsBar())}
    <section class="card ahu-ranking"><div class="card-head"><div class="card-title ahu-panel-title"><span class="spark">◎</span>AI 今日 Top 5 改善機會</div><span class="more">更多 ›</span></div><div class="table-wrap"><table><thead><tr><th>排名</th><th>AHU 編號</th><th>場域</th><th>AI 預估節能率</th></tr></thead><tbody><tr><td>1</td><td>AH-3F-09A</td><td>巨城本館</td><td class="bad">18.2%</td></tr><tr><td>2</td><td>AH-2F-03</td><td>創藝大樓</td><td class="bad">17.4%</td></tr><tr><td>3</td><td>AH-4F-02</td><td>巨城本館</td><td class="warn">14.8%</td></tr><tr><td>4</td><td>AH-B1-01</td><td>巨城本館</td><td class="warn">13.2%</td></tr><tr><td>5</td><td>AH-RF-01</td><td>威秀影城</td><td class="warn">12.6%</td></tr></tbody></table></div></section>
  </div>
  <div class="ahu-three-grid">${card('<span class="spark">◔</span>整體節電量構成（2026 年累計）',ahuDonutBlock())}${card('<span class="spark">▥</span>月度節電趨勢',`<div class="chart-box ahu-chart-md">${svgBars([{name:'2025',data:[65,72,81,90,98,102,107,112,118,121,124,128],color:'#a7b8c7'},{name:'2026',data:[75,84,92,101,110,118,123,132,126,139,147,153],color:'#1597f5'}],months,{max:180})}</div><div class="card-sub" style="text-align:right">2026 累計節電量 <b style="color:var(--ink)">1,280,500 kWh</b>　<span class="good"><b>▲12%</b></span></div>`)}<section class="card"><div class="card-head"><div class="card-title ahu-panel-title"><span class="spark">✦</span>AI 綜合分析與建議</div>${pill('AI 分析完成','good')}</div><div class="ahu-summary-list"><div class="ahu-summary-item"><span class="ahu-num green">1</span><div><strong>硬體改善已帶來顯著節電</strong><p>EC FAN / VFD 改善後，整體平均節電率約 18.6%，年度累計節電達 1.28 GWh。</p></div></div><div class="ahu-summary-item"><span class="ahu-num">2</span><div><strong>AI 仍發現額外最佳化空間</strong><p>影子模式估計尚有約 356 MWh/年的潛力，優先集中於 Top 5 AHU。</p></div></div><div class="ahu-summary-item"><span class="ahu-num warn">3</span><div><strong>建議先人工試驗再驗證</strong><p>依場域條件逐台調整 VFD / EC Fan 控制，再以 M&amp;V 驗證成效，不直接由 AI 下控。</p></div></div></div></section></div>`;
}
function renderAhuUnit(){
  const u=ahuUnits[state.ahuUnit],s=unitSeries(u.baseline,u.actual,16),labels=['4/01','4/03','4/05','4/07','4/09','4/11','4/13','4/15','4/17','4/19','4/21','4/23','4/25','4/27','4/29','4/30'];
  const saving=u.baseline-u.actual,savingPct=saving/u.baseline*100,cum=Math.round(saving*30),fan=[66,68,70,67,65,62,60,59,58,60,61,59,57,58,60,56],valve=[42,39,35,33,34,31,29,28,26,27,29,25,24,27,28,26],temp=[23.9,24.0,24.2,24.1,23.8,24.0,24.1,23.9,23.8,23.7,23.9,24.0,23.8,23.9,24.1,23.8];
  return ahuPageHead('ahu-unit','單台 AHU 成效驗證','以正規化 Baseline 比較改善後實際用電，驗證節能效益並同步守住舒適度。')+
  `<div class="ahu-controls"><label>場域：<span class="control-btn">${u.siteName} (${u.bms})</span></label><label>AHU 編號：${ahuUnitSelect()}</label><label>改善方式：<span class="control-btn">${u.type} + 控制最佳化</span></label><label style="margin-left:auto">期間：<span class="control-btn active">2026/04/01 – 2026/04/30</span></label></div>
  <div class="ahu-kpi-grid">${kpi('▥','Baseline<br>(正規化後)',fmt(u.baseline),'kWh/日','相似負載＋外氣條件','blue')}${kpi('🍃','Actual<br>(實際用電)',fmt(u.actual),'kWh/日',`▼ ${savingPct.toFixed(1)}%　vs Baseline`,'good','green')}${kpi('ϟ','Verified Saving<br>(已驗證節電)',fmt(saving),'kWh/日',`▼ ${savingPct.toFixed(1)}%`,'good')}${kpi('◒','累計節電量<br>(本月)',fmt(cum),'kWh','M&V 驗證區間','good','green')}${kpi('◷','運轉時數<br>(本期)',fmt(u.hours),'hr','全天/營業條件正規化','blue')}${kpi('♨','溫度達標率<br>(Zone)',u.tempCompliance.toFixed(1),'%','舒適度維持正常','good')}</div>
  <div class="ahu-big-grid">${card(`<span class="spark">▥</span>${state.ahuUnit} 用電量趨勢（Normalized Baseline vs Actual）`,`<div class="chart-box ahu-chart-lg">${svgLine([{name:'Normalized Baseline',data:s.baseline,color:'#1597f5'},{name:'Actual',data:s.actual,color:'#18b987'}],labels,{min:Math.min(...s.actual)*.8,max:Math.max(...s.baseline)*1.12,decimals:0,labelEvery:2})}</div><div class="ahu-statusbar">${pill(`Verified Saving ${savingPct.toFixed(1)}%`,'good')}<span class="card-sub">節電區間＝Baseline − Actual；正式值依 M&V 模型計算</span></div>`)}<section class="card"><div class="card-head"><div class="card-title ahu-panel-title"><span class="spark">✦</span>成效驗證重點</div></div><div class="ahu-summary-list"><div class="ahu-summary-item"><span class="ahu-num">1</span><div><strong>相同負載條件比較</strong><p>以相似營業時段、人流與區域負載做正規化，排除使用行為差異。</p></div></div><div class="ahu-summary-item"><span class="ahu-num">2</span><div><strong>相同天氣條件比較</strong><p>納入外氣溫濕度條件，建立 Normalized Baseline，避免氣候造成假節能。</p></div></div><div class="ahu-summary-item"><span class="ahu-num green">3</span><div><strong>改善後實際低於 Baseline</strong><p>在相似條件下 Actual 持續低於基準，可作為設備/控制改善成效依據。</p></div></div></div></section></div>
  <div class="ahu-two-grid">${card('<span class="spark">▥</span>運轉參數與環境趨勢',`<div class="chart-box ahu-chart-md">${svgLine([{name:'Fan %',data:fan,color:'#735ce8'},{name:'CHW Valve %',data:valve,color:'#1597f5'},{name:'Zone Temp x2',data:temp.map(v=>v*2),color:'#f5aa1e'}],labels,{min:20,max:80,decimals:0,labelEvery:2})}</div>`)}<section class="card ahu-verified"><div class="card-head"><div class="card-title ahu-panel-title"><span class="spark">✓</span>舒適度確保</div>${pill('運轉正常','good')}</div><div class="ahu-guardrail"><div class="ahu-guard"><span>Zone 溫度</span><b>${u.temp.toFixed(1)}°C</b><small>✓ 22–26°C</small></div><div class="ahu-guard"><span>CO₂</span><b>${u.co2} ppm</b><small>✓ &lt; 800 ppm</small></div><div class="ahu-guard"><span>溫度達標率</span><b>${u.tempCompliance.toFixed(1)}%</b><small>✓ 合格</small></div><div class="ahu-guard"><span>顧客舒適警示</span><b>0</b><small>✓ 無異常</small></div></div><div class="ahu-disclaimer" style="margin-top:10px"><b>結論：</b>${state.ahuUnit} 在相似負載與外氣條件下，改善後用電降低約 ${savingPct.toFixed(1)}%，同時舒適度維持正常，具備可驗證的節能效益。</div></section></div>`;
}
function renderAhuShadow(){
  const u=ahuUnits[state.ahuUnit],s=shadowSeries(u,16),labels=['00','02','04','06','08','10','12','14','16','18','20','22','23','24','25','26'],rec=Math.round(u.actual*(1-u.shadow/100)),delta=u.actual-rec;
  return ahuPageHead('ahu-shadow','AI Shadow Mode 影子模式','在不直接控制設備的前提下，AI 模擬最佳化機會、估計潛在節能並提供可執行建議。')+
  `<div class="shadow-mode-banner"><div><b>◉ 建議模式 Advisory Mode｜尚未下控 (Not Controlling)</b><br><span>AI 僅做分析、推估與建議，不會變更任何設備的實際控制設定。</span></div>${pill('AI 持續監測中','good')}</div><div class="ahu-controls"><label>AHU 編號：${ahuUnitSelect()}</label><label>場域：<span class="control-btn">${u.siteName} (${u.bms})</span></label><label style="margin-left:auto">期間：<span class="control-btn active">2026/04/17 – 2026/04/24</span></label></div>
  <div class="ahu-kpi-grid">${kpi('🍃','AI 影子模式潛在節能<br>(Counterfactual)',u.shadow.toFixed(1),'%','尚未落實','good','green')}${kpi('▥','再改善百分比<br>(相較目前運轉)',u.shadow.toFixed(1),'%',`約 ${fmt(delta)} kWh/日`,'good')}${kpi('◎','AI 建議可信度<br>(Confidence)',u.confidence,'%','相似工況模型評估','good')}${kpi('ϟ','實際用電<br>(Actual)',fmt(u.actual),'kWh/日','目前實際運轉','blue')}${kpi('✦','AI 建議用電<br>(Recommended)',fmt(rec),'kWh/日',`▼ ${fmt(delta)} kWh/日`,'good','green')}${kpi('♡','舒適度風險<br>(Comfort Risk)','低','','Guardrail 內','good')}</div>
  <div class="ahu-big-grid">${card(`<span class="spark">▥</span>${state.ahuUnit} 用電趨勢比較`,`<div class="chart-box ahu-chart-lg">${svgLine([{name:'Baseline',data:s.baseline,color:'#9eb3c7',dash:true},{name:'Actual',data:s.actual,color:'#1597f5'},{name:'AI Shadow',data:s.recommended,color:'#18b987',dash:true}],labels,{min:Math.min(...s.recommended)*.8,max:Math.max(...s.baseline)*1.1,decimals:0,labelEvery:2})}</div>`)}<section class="card"><div class="card-head"><div class="card-title ahu-panel-title"><span class="spark">🧠</span>AI 推論與建議</div><span class="card-sub">尚未下發控制指令</span></div><div class="ahu-summary-list"><div class="ahu-summary-item"><span class="ahu-num">1</span><div><strong>判斷證據 Evidence</strong><p>風機頻率長時間偏高、CHW Valve 偏低、Zone 已達舒適區，類似工況存在過度送風。</p></div></div><div class="ahu-summary-item"><span class="ahu-num green">2</span><div><strong>AI 結論 Conclusion</strong><p>在維持舒適的前提下，預估仍有約 ${u.shadow.toFixed(1)}% 的用電改善空間。</p></div></div><div class="ahu-summary-item"><span class="ahu-num warn">3</span><div><strong>AI 建議 Recommendation</strong><p>建議人工試降風機頻率約 10–15%，並同步觀察 Zone Temp、CO₂ 與 CHW Valve。</p></div></div><div class="ahu-summary-item"><span class="ahu-num">4</span><div><strong>觀察條件</strong><p>若 Zone Temp / CO₂ / Valve 逼近上限，停止調降；先以 15–30 分鐘試驗驗證。</p></div></div></div></section></div>
  <div class="ahu-two-grid">${card('<span class="spark">✤</span>風機頻率比較',`<div class="chart-box ahu-chart-md">${svgLine([{name:'Actual Fan %',data:[64,61,62,68,72,74,70,69,66,64,67,70,68,65,66,64],color:'#1597f5'},{name:'AI Recommended %',data:[52,49,50,54,57,59,56,55,53,51,54,56,55,52,53,52],color:'#18b987',dash:true}],labels,{min:35,max:85,decimals:0,labelEvery:2})}</div><div class="ahu-statusbar">${pill(`Actual ${u.fan}%`,'blue')}${pill(`AI 建議 ${u.fanRec}%`,'good')}</div>`)}<section class="card ahu-verified"><div class="card-head"><div class="card-title ahu-panel-title"><span class="spark">🛡</span>Comfort Guardrail 舒適度保護</div>${pill('安全範圍內','good')}</div><div class="ahu-guardrail"><div class="ahu-guard"><span>Zone 溫度</span><b>${u.temp.toFixed(1)}°C</b><small>✓ 22–26°C</small></div><div class="ahu-guard"><span>CHW Valve</span><b>${u.valve}%</b><small>✓ 有裕度</small></div><div class="ahu-guard"><span>CO₂</span><b>${u.co2} ppm</b><small>✓ &lt;800</small></div><div class="ahu-guard"><span>Comfort Alarm</span><b>0</b><small>✓ 無異常</small></div></div><div class="ahu-disclaimer" style="margin-top:10px"><b>影子模式潛在效益：</b>此為 Counterfactual Estimate，不代表已實現節電；只有人工採納並經 M&amp;V 驗證後，才列入 Verified AI-assisted Saving。</div></section></div>`;
}
function ahuWaterfall(){
  const W=720,H=300,pL=62,pR=20,pT=28,pB=54,max=4200,vals=[4010.86,3255.86,3018.79,2730.36],x=[85,240,395,565],bw=82,y=v=>pT+(H-pT-pB)*(1-v/max),steps=[{x:x[0],from:0,to:4010.86,label:'改善前基準',value:'4,010,860',color:'#9eb3c7'},{x:x[1],from:3255.86,to:4010.86,label:'EC FAN / VFD',value:'−755,000',color:'#18b987'},{x:x[2],from:3018.79,to:3255.86,label:'既有控制改善',value:'−237,070',color:'#36bfe0'},{x:x[3],from:2730.36,to:3018.79,label:'AI 建議採納',value:'−288,430',color:'#735ce8'}];
  let o=`<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none">`;for(let i=0;i<5;i++){const v=max*(1-i/4),yy=y(v);o+=`<line class="grid-line" x1="${pL}" y1="${yy}" x2="${W-pR}" y2="${yy}"/><text class="axis-label" x="3" y="${yy+4}">${Math.round(v*1000).toLocaleString()}</text>`}steps.forEach(s=>{const yy=y(s.to),hh=Math.abs(y(s.from)-y(s.to));o+=`<rect x="${s.x}" y="${yy}" width="${bw}" height="${hh}" rx="3" fill="${s.color}"></rect><text x="${s.x+bw/2}" y="${yy-8}" text-anchor="middle" fill="var(--ink)" font-size="13" font-weight="800">${s.value}</text><text class="axis-label" x="${s.x+bw/2}" y="${H-20}" text-anchor="middle">${s.label}</text>`});const fy=y(2730.36);o+=`<rect x="655" y="${fy}" width="${bw-8}" height="${H-pB-fy}" rx="3" fill="#1597f5"></rect><text x="${655+(bw-8)/2}" y="${fy-8}" text-anchor="middle" fill="var(--ink)" font-size="13" font-weight="800">2,730,360</text><text class="axis-label" x="${655+(bw-8)/2}" y="${H-20}" text-anchor="middle">目前耗能</text>`;return o+'</svg>';
}
function renderAhuContribution(){
  const months=['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'];
  return ahuPageHead('ahu-contribution','AI 最佳化貢獻與驗證','把設備改善、既有控制、AI 建議採納與 Shadow 潛力拆開量化，清楚證明 AI 的實際價值。')+
  `<div class="ahu-controls"><label>期間：<span class="control-btn active">年</span><span class="control-btn">季</span><span class="control-btn">月</span></label><label>年份：<span class="control-btn active">2026 年⌄</span></label><label>場域：${ahuSiteSeg()}</label></div><div class="ahu-kpi-grid">${kpi('⚙','設備改善節電<br>(EC FAN / VFD)','755,000','kWh','已實現','good','green')}${kpi('☷','既有控制改善<br>(排程 / Reset)','237,070','kWh','已實現','good')}${kpi('🧠','AI 建議已驗證節電<br>(人工採納)','288,430','kWh','Verified','good')}${kpi('◌','AI Shadow 尚未落實<br>(待採納)','356,000','kWh','Counterfactual','warn')}${kpi('🍃','年度累計節電貢獻','1,280,500','kWh','▲12%　較去年','good','green')}${kpi('▤','累計採納次數','58','次','▲32%　較去年','good')}</div>
  <div class="ahu-big-grid">${card('<span class="spark">✦</span>節能貢獻組成 Waterfall',`<div class="ahu-waterfall">${ahuWaterfall()}</div><div class="ahu-statusbar">${pill('Realized Saving 1,280,500 kWh','good')}<span class="card-sub">改善前基準 → 硬體 → 控制 → AI 建議採納 → 目前耗能</span></div>`)}<section class="card"><div class="card-head"><div class="card-title ahu-panel-title"><span class="spark">↕</span>Recommendation Timeline</div><span class="more">2026/04</span></div><div class="ahu-timeline"><div class="ahu-timeline-item"><div class="ahu-timeline-time">04/10<br>14:32</div><div class="ahu-timeline-node"><i>AI</i></div><div class="ahu-timeline-copy"><b>AI 發現與建議</b><p>偵測 AH-3F-09A 送風偏高，建議人工試降風機頻率 10%。</p></div></div><div class="ahu-timeline-item"><div class="ahu-timeline-time">04/11<br>09:15</div><div class="ahu-timeline-node"><i style="background:var(--green)">✓</i></div><div class="ahu-timeline-copy"><b>營運人員採納</b><p>現場確認舒適裕度後，以人工方式調整 VFD 設定。</p></div></div><div class="ahu-timeline-item"><div class="ahu-timeline-time">04/11<br>14:00</div><div class="ahu-timeline-node"><i style="background:var(--amber)">▥</i></div><div class="ahu-timeline-copy"><b>實際量測回應</b><p>功率下降且 Zone Temp / CO₂ 維持正常，進入持續驗證。</p></div></div><div class="ahu-timeline-item"><div class="ahu-timeline-time">04/12<br>08:30</div><div class="ahu-timeline-node"><i style="background:var(--green)">✓</i></div><div class="ahu-timeline-copy"><b>AI 驗證節電</b><p>連續觀察 24 小時後，依 M&amp;V 判定節電成立。</p></div></div></div></section></div>
  <div class="ahu-three-grid"><section class="card ahu-verified"><div class="card-head"><div class="card-title ahu-panel-title"><span class="spark">✓</span>Verified AI-assisted Saving</div></div><div class="ahu-stat-row"><div class="ahu-stat"><span>已驗證節電量</span><b>288,430</b><span>kWh</span></div><div class="ahu-stat"><span>節電率</span><b>7.2%</b></div><div class="ahu-stat"><span>已採納次數</span><b>58</b></div><div class="ahu-stat"><span>驗證成功率</span><b>92%</b></div></div><div class="chart-box ahu-chart-sm">${svgBars([{name:'月節電',data:[12,18,21,25,27,30,33,32,29,24,20,17],color:'#18b987'}],months,{max:40})}</div></section><section class="card"><div class="card-head"><div class="card-title ahu-panel-title"><span class="spark">◎</span>Shadow Opportunity vs Verified</div></div><div class="ahu-compare"><div class="ahu-compare-box ahu-verified"><span>已驗證節電 Realized</span><b class="good">288,430</b><span>kWh｜已人工採納＋M&amp;V</span></div><div class="ahu-compare-box ahu-shadow"><span>尚未落實潛力 Shadow</span><b class="warn">356,000</b><span>kWh｜尚未下控</span></div></div><div class="ahu-disclaimer" style="margin-top:10px">若高信心建議逐步完成人工試驗與驗證，可把 Shadow Opportunity 逐步轉成 Verified Saving。</div></section><section class="card"><div class="card-head"><div class="card-title ahu-panel-title"><span class="spark">▤</span>重點洞察與建議</div></div><div class="ahu-summary-list"><div class="ahu-summary-item"><span class="ahu-num green">1</span><div><strong>AI 已產生可驗證價值</strong><p>已驗證 288,430 kWh，不把 Shadow 預估混入實際節電。</p></div></div><div class="ahu-summary-item"><span class="ahu-num warn">2</span><div><strong>尚有 356 MWh 潛力待驗證</strong><p>優先處理高信心、低舒適度風險的 AHU。</p></div></div><div class="ahu-summary-item"><span class="ahu-num">3</span><div><strong>建立推薦→採納→驗證閉環</strong><p>每一筆 AI 建議都保留證據、操作員回覆與驗證結果。</p></div></div></div></section></div>`;
}
function renderAhuHealth(){
  const labels=['00','02','04','06','08','10','12','14','16','18','20','22'];
  return ahuPageHead('ahu-health','舒適度・設備健康・AI 監督','節能不犧牲舒適；AI 同時監督設備健康、AFDD 異常與數據品質。')+
  `<div class="ahu-kpi-grid">${kpi('♨','溫度合規率<br>(22–26°C)','98.6','%','▲2.1%　較昨日','good')}${kpi('CO₂','CO₂ 合規率<br>(≤800 ppm)','97.8','%','▲1.5%　較昨日','good','green')}${kpi('🔔','舒適度警報<br>(目前)','2','','▼60%　較昨日','good')}${kpi('🧠','AI 數據可信度<br>(整體)','99.2','%','▲0.3%','good')}${kpi('◷','超溫時間<br>(本日累計)','18','分鐘','▼65%','good')}${kpi('🔧','待處理異常數<br>(設備 / AFDD)','6','','▲2　較昨日','bad')}</div>
  <div class="ahu-three-grid">${card('<span class="spark">♨</span>室內舒適度趨勢（24 小時）',`<div class="chart-box ahu-chart-md">${svgLine([{name:'Zone Temp',data:[23.5,23.7,24.0,24.1,23.9,24.2,24.4,24.3,24.0,23.8,24.1,24.2],color:'#1597f5'},{name:'Outdoor Temp',data:[25.7,25.9,26.2,26.8,27.5,28.2,28.7,28.5,27.8,27.1,26.6,26.1],color:'#9eb3c7',dash:true}],labels,{min:22,max:30,decimals:1,labelEvery:2})}</div>${pill('全天 98.6% 維持舒適範圍','good')}`)}${card('<span class="spark">CO₂</span>CO₂ 濃度（24 小時）',`<div class="chart-box ahu-chart-md">${svgLine([{name:'CO₂ ppm',data:[480,500,520,510,560,610,650,690,720,680,620,560],color:'#1597f5'},{name:'Limit',data:[800,800,800,800,800,800,800,800,800,800,800,800],color:'#18b987',dash:true}],labels,{min:300,max:900,decimals:0,labelEvery:2})}</div>${pill('97.8% 符合室內空氣品質條件','good')}`)}<section class="card"><div class="card-head"><div class="card-title ahu-panel-title"><span class="spark">🧠</span>AI 監督摘要</div>${pill('持續監測中','good')}</div><div class="ahu-summary-list"><div class="ahu-summary-item"><span class="ahu-num green">✓</span><div><strong>持續監測舒適度</strong><p>即時分析溫度、濕度、CO₂，避免節能造成環境品質下降。</p></div></div><div class="ahu-summary-item"><span class="ahu-num">⚙</span><div><strong>設備健康預警</strong><p>監測濾網壓差、同頻率功率、閥門回授與風機特徵。</p></div></div><div class="ahu-summary-item"><span class="ahu-num warn">!</span><div><strong>AFDD 與數據品質</strong><p>異常先分級，再交由工程人員確認；低可信數據不直接產生節能結論。</p></div></div></div></section></div>
  <div class="ahu-two-grid"><section class="card ahu-health-table"><div class="card-head"><div class="card-title ahu-panel-title"><span class="spark">⚙</span>設備健康監控</div><span class="more">更多 ›</span></div><div class="table-wrap"><table><thead><tr><th>設備</th><th>健康狀態</th><th>關鍵問題</th><th>詳細數值</th><th>處理建議</th></tr></thead><tbody><tr><td>AH-1F-01</td><td>${pill('注意','warn')}</td><td>濾網壓差偏高</td><td>320 Pa</td><td>安排濾網檢查</td></tr><tr><td>AH-2F-03</td><td>${pill('良好','good')}</td><td>運轉正常</td><td>—</td><td>持續監測</td></tr><tr><td>AH-3F-09A</td><td>${pill('異常','bad')}</td><td>同頻率風機功率偏高</td><td>+18%</td><td>檢查風機 / EC 模組</td></tr><tr><td>AH-4F-02</td><td>${pill('注意','warn')}</td><td>CHW Valve 命令/回授偏差</td><td>40% / 18%</td><td>檢查 actuator</td></tr><tr><td>AH-RF-01</td><td>${pill('注意','warn')}</td><td>感測器可信度偏低</td><td>78%</td><td>校正感測器</td></tr></tbody></table></div></section><section class="card"><div class="card-head"><div class="card-title ahu-panel-title"><span class="spark">⌁</span>AFDD / 智慧診斷列表</div><span class="more">更多 ›</span></div><div class="ahu-afdd-row ahu-afdd-head"><span>時間</span><span>設備</span><span>異常描述</span><span>嚴重度</span><span>狀態</span></div><div class="ahu-afdd-row"><span>09/10 10:42</span><span>AH-3F-09A</span><span>風機功率特徵異常，疑似阻力增加</span>${pill('高','bad')}${pill('待處理','warn')}</div><div class="ahu-afdd-row"><span>09/10 09:15</span><span>AH-4F-02</span><span>冰水閥命令與回授偏差 &gt; 15%</span>${pill('中','warn')}${pill('處理中','blue')}</div><div class="ahu-afdd-row"><span>09/09 16:40</span><span>CWP-02</span><span>振動頻譜異常，建議巡檢軸承</span>${pill('高','bad')}${pill('待處理','warn')}</div><div class="ahu-afdd-row"><span>09/09 13:22</span><span>AH-RF-01</span><span>回風溫度感測器可信度 78%</span>${pill('低','blue')}${pill('已派單','good')}</div></section></div>`;
}

Object.assign(renderers,{'ahu-overview':renderAhuOverview,'ahu-unit':renderAhuUnit,'ahu-shadow':renderAhuShadow,'ahu-contribution':renderAhuContribution,'ahu-health':renderAhuHealth});
const bindPageBase=bindPage;
bindPage=function(){bindPageBase();$$('[data-ahu-page]').forEach(btn=>btn.addEventListener('click',()=>{state.page=btn.dataset.ahuPage;render();window.scrollTo({top:0,behavior:'smooth'});}));const unit=$('#ahuUnitSelect');if(unit)unit.addEventListener('change',e=>{state.ahuUnit=e.target.value;render();});};
