(function(){
const svgChiller=(on=false)=>`<svg viewBox="0 0 120 62" class="ca-machine"><rect x="16" y="23" width="82" height="26" rx="11"/><circle cx="35" cy="36" r="8"/><circle cx="82" cy="36" r="8"/><rect x="28" y="15" width="58" height="10" rx="3"/><path d="M98 30h8v13h-8M12 29h6v14h-6"/></svg>`;
const svgTower=()=>`<svg viewBox="0 0 74 72" class="ca-flow-icon"><path d="M20 10h34l7 52H13l7-52Z"/><path d="M25 22h24M23 32h28M20 42h34M17 52h40"/></svg>`;
const svgPump=()=>`<svg viewBox="0 0 74 72" class="ca-flow-icon"><circle cx="35" cy="36" r="18"/><path d="M35 18v36M17 36h36M53 31h12v10H53M9 31h8v10H9"/></svg>`;
const gauge=(v,label)=>`<div class="ca-gauge"><div><small>${label}</small><b>${v}</b><span>kW/RT</span></div></div>`;
const kpi=(icon,label,val,meta,cls='')=>`<article class="ca-kpi ${cls}"><div class="ca-kpi-label"><span>${icon}</span>${label}</div><b>${val}</b><small>${meta}</small></article>`;
function renderPlant(){return `<div class="ca-page">
<section class="ca-hero"><div><span>BIG CITY × DELTA ENERGY</span><h1>冰水機房智慧駕駛艙</h1><p>Chiller Plant Smart Cockpit｜即時監測主機、泵浦、水側效率與 AI 最佳化建議</p></div><div class="ca-mode-note">深／淺模式同步切換</div></section>
<div class="ca-kpis">${kpi('◔','系統效率','0.68 kW/RT','優於展示基準 12%','good')}${kpi('❄','即時冷量','3,080 RT','較昨日同期 +5.2%')}${kpi('ϟ','主機總功率','2,094 kW','較昨日同期 -6.8%','good')}${kpi('♨','系統 ΔT','5.1°C','目標 5.0°C','good')}${kpi('◉','二次泵頻率','43 Hz','最佳區間 40–50 Hz','good')}${kpi('AI','AI 今日建議','4 項','預估節能 6–8%','warn')}</div>
<div class="ca-grid plant-top">
<section class="ca-card plant-eff"><div class="ca-card-title">整體機房效率 <small>System Efficiency</small></div><div class="plant-eff-body">${gauge('0.68','整體效率')}<div class="plant-metrics"><div><span>CHWS</span><b>7.0°C</b></div><div><span>CHWR</span><b>12.1°C</b></div><div><span>CWS</span><b>28.6°C</b></div><div><span>CWR</span><b>32.4°C</b></div><div><span>系統負載</span><b>67%</b></div></div></div></section>
<section class="ca-card chillers"><div class="ca-card-head"><div class="ca-card-title">主機運轉狀態</div><span class="ai-badge">AI 最佳組合　CH-03 + CH-05 + CH-06</span></div><div class="chiller-row">${[['CH-01','待機',0,'0.00',0],['CH-02','待機',0,'0.00',0],['CH-03','運轉中',85,'0.66',1],['CH-04','停機',0,'—',-1],['CH-05','運轉中',78,'0.70',1],['CH-06','運轉中',76,'0.69',1]].map(c=>`<article class="chiller ${c[4]===1?'on':c[4]===-1?'fault':''}">${svgChiller(c[4]===1)}<b>${c[0]}</b><span class="dot"></span><small>${c[1]}</small><div class="load"><i style="width:${c[2]}%"></i></div><strong>${c[2]}%</strong><em>${c[3]} kW/RT</em></article>`).join('')}</div></section></div>
<div class="ca-grid plant-mid">
<section class="ca-card"><div class="ca-card-title">系統流程圖 <small>System Flow Diagram</small></div><div class="flow-wrap"><div>${svgTower()}<b>冷卻水塔</b></div><span class="pipe green">→</span><div>${svgPump()}<b>冷卻水泵</b></div><span class="pipe green">→</span><div>${svgChiller(true)}<b>冰水主機</b></div><span class="pipe blue">→</span><div>${svgPump()}<b>一次泵</b></div><span class="pipe blue">→</span><div>${svgPump()}<b>二次泵</b></div><span class="pipe blue">→ AHU</span></div></section>
<section class="ca-card"><div class="ca-card-head"><div class="ca-card-title">近 24 小時趨勢</div><div class="mini-tabs"><b>今日</b><span>本週</span><span>本月</span></div></div><svg viewBox="0 0 520 185" class="trend-svg"><g class="grid"><line x1="34" y1="25" x2="500" y2="25"/><line x1="34" y1="75" x2="500" y2="75"/><line x1="34" y1="125" x2="500" y2="125"/></g><polyline points="35,135 75,125 115,112 155,90 195,83 235,62 275,54 315,68 355,72 395,82 435,88 495,94" class="l1"/><polyline points="35,145 75,139 115,130 155,121 195,110 235,96 275,82 315,70 355,65 395,67 435,73 495,80" class="l2"/><line x1="355" y1="18" x2="355" y2="150" class="focus"/><circle cx="355" cy="72" r="5"/></svg></section></div>
<div class="ca-grid plant-bottom"><section class="ca-card"><div class="ca-card-title">AI 診斷與優化建議</div><div class="recommend-list">${[['低 ΔT 風險','目前 ΔT 5.1°C，已接近目標下限。','人工試降二次側 DP 5 kPa，觀察 15 分鐘。','6–8%'],['二次側過度送水','二次泵長時間高頻，部分時段負載偏低。','建議人工試降頻率並監看最不利端。','3–5%'],['部分 AHU 閥位偏低','3F 區域部分閥位低於 20%。','檢查盤管控制與末端需求。','2–4%'],['冷卻水塔效率可優化','CWR 32.4°C，仍有優化空間。','調整風扇台數與轉速策略。','3–6%']].map((r,i)=>`<div class="rec"><span>${i+1}</span><b>${r[0]}</b><p>${r[1]}</p><em>${r[2]}</em><strong>${r[3]}</strong></div>`).join('')}</div></section><section class="ca-card"><div class="ca-card-title">即時警示／關注事項</div><div class="alert-list"><div class="alert fault">● CH-04 主機故障停機 <b>待處理</b></div><div class="alert warn">▲ 2F 回水溫度偏高 <b>監測中</b></div><div class="alert warn">▲ CT-03 出水溫度偏高 <b>監測中</b></div><div class="alert good">● P-02 頻率波動已改善 <b>已改善</b></div></div></section></div>
<div class="ca-note">Demo Data｜本頁為展示資料，不代表實際運轉數據。</div></div>`}
function renderInsights(){return `<div class="ca-page analyst">
<section class="ca-hero"><div><span>BIG CITY × DELTA ENERGY</span><h1>AI 能源分析師</h1><p>AI Energy Analyst｜將 EMS / BMS 數據轉化為現象、證據、原因與可執行建議</p></div><div class="ca-mode-note">Explainable AI</div></section>
<div class="ca-kpis analyst-kpis">${kpi('AI','今日 AI 洞察','7 項','較昨日 +2','purple')}${kpi('🍃','已確認節能機會','NT$ 1.2M / 年','預估年減碳 420 噸 CO₂e','good')}${kpi('⚠','異常風險','3 項','較昨日 -1','warn')}${kpi('◈','分析可信度','87%','基於歷史數據與 AI 模型')}${kpi('◎','持續分析','24/7','讓每一度電創造更大價值')}</div>
<div class="ca-grid analyst-main"><section class="ca-card issue"><div class="ca-card-head"><div class="ca-card-title">今日首要議題：低 ΔT 導致輸送效率下降</div><span class="risk-chip">影響重大</span></div><p class="issue-sub">3F–5F 區域 14:00–16:00 冰水 ΔT 顯著下降，導致流量上升、用電增加與整體輸送效率下降。</p><div class="reason-chain">${[['現象','冰水 ΔT 5.8→3.2°C\n冰水泵用電 +28%'],['證據','3F–5F 溫差偏低\n流量增加 32%'],['可能原因','二次側流量過大\n部分 AHU 控制不佳'],['建議動作','調整水閥與泵浦\n檢查 AHU 盤管'],['預估效益','280,000 kWh/年\n約 NT$1.0M/年']].map((x,i)=>`<div class="reason r${i}"><b>${x[0]}</b><p>${x[1].replace('\n','<br>')}</p></div>`).join('<span class="arrow">→</span>')}</div></section>
<section class="ca-card timeline"><div class="ca-card-title">AI 事件解讀 <small>AI Analysis Timeline</small></div><div class="timeline-list">${[['14:40','3F–5F 冰水 ΔT 降至 3.2°C'],['14:05','冰水泵流量上升 32%'],['13:10','外氣溫度快速上升 +3.8°C'],['11:20','AHU-3 回風溫度偏高'],['08:30','系統運行正常']].map((x,i)=>`<div><time>${x[0]}</time><span class="t-dot t${i}"></span><p>${x[1]}</p></div>`).join('')}</div></section></div>
<div class="ca-grid analyst-mid"><section class="ca-card"><div class="ca-card-title">冰水系統效率趨勢</div><svg viewBox="0 0 620 190" class="trend-svg big"><g class="grid"><line x1="35" y1="30" x2="600" y2="30"/><line x1="35" y1="80" x2="600" y2="80"/><line x1="35" y1="130" x2="600" y2="130"/></g><rect x="360" y="18" width="105" height="135" class="window"/><polyline points="35,62 85,72 135,94 185,85 235,74 285,66 335,63 385,58 435,63 485,69 535,64 595,71" class="l3"/><polyline points="35,105 85,103 135,98 185,91 235,85 285,79 335,72 385,69 435,76 485,85 535,91 595,96" class="l1"/><polyline points="35,55 85,60 135,72 185,68 235,58 285,48 335,43 385,38 435,42 485,49 535,52 595,51" class="l2 dash"/></svg></section><section class="ca-card opportunity"><div class="ca-card-title">節能機會分布</div><div class="opp-body"><div class="opp-donut"><b>NT$1.2M</b><span>/ 年</span></div><div><p>冰水主機 <b>38%</b></p><p>冰水泵浦 <b>27%</b></p><p>AHU 空調箱 <b>18%</b></p><p>需量管理 <b>10%</b></p><p>其他 <b>7%</b></p></div></div></section></div>
<div class="ca-grid analyst-bottom"><section class="ca-card"><div class="ca-card-title">Top Opportunities</div><div class="rank-list">${[['優化二次側水閥開度','NT$ 1.0M / 年'],['AHU 變頻器策略優化','NT$ 320K / 年'],['冰水泵變頻控制優化','NT$ 280K / 年'],['需量反應排程優化','NT$ 180K / 年']].map((x,i)=>`<div><span>${i+1}</span><b>${x[0]}</b><strong>${x[1]}</strong></div>`).join('')}</div></section><section class="ca-card"><div class="ca-card-title">Top Risks</div><div class="rank-list risk">${['熱浪高負載','感測器數據偏移','低 ΔT 持續','排程設定異常'].map((x,i)=>`<div><span>${i+1}</span><b>${x}</b><strong>${i===0?'高風險':i<3?'中風險':'低風險'}</strong></div>`).join('')}</div></section><section class="ca-card copilot"><div class="ca-card-title">AI Copilot 智慧助理</div><button>為什麼昨日 14:00–16:00 用電上升？</button><button>如何進一步改善低 ΔT？</button><div class="answer">主要原因為外氣溫度上升，同時二次側流量增加 32%，造成輸送效率下降。建議先確認最不利端後，再逐步降低 DP 設定。</div><input placeholder="輸入您的問題…"></section></div>
<div class="ca-note">Demo Data｜數據為模擬情境，僅供 UI / Demo 展示。</div></div>`}
if(typeof renderers!=='undefined'){renderers.plant=renderPlant;renderers.insights=renderInsights;}
})();